### ISSUE TITLE
Native MacOS Support

### ISSUE THREAD

**Issue by danslo** [sidkshatriya/dontbug#1]
This issue is not so much a feature request, as I may be able to help out in this regard (I've been involved in porting HHVM to OSX for example).

What would be the general areas to look at to make this run on MacOS natively?

**Comment by sidkshatriya** [comment]
Thanks for opening ticket #1 on this project :-)

Dontbug depends significantly on [mozilla/rr](https://github.com/mozilla/rr) which is only available for Linux. And its very difficult to port mozilla/rr to other operating systems as it requires some very specific capabilities that are either only available on Linux or undocumented/unavailable/unexposed in other operating systems like macOS.

So sadly at this point I would say its unlikely that Dontbug is going to be available on other operating systems anytime soon. Your best bet is to run Dontbug in a Linux VM on those other OSes.

Here is an interesting blog post on this issue: 
https://joneschrisg.wordpress.com/2015/01/29/rr-on-os-x-can-it-be-ported/

There might be some other discussions you can find on the internet / rr mailing lists on this topic.

@rocallahan might also be able to say if there have been some developments on this issue since the blog post was written and if there are some other approaches (like lightweight instrumentation) that can be considered on macOS.

**Comment by rocallahan** [comment]
No new developments.
